{% set version = "0.17.19" %}

package:
  name: esbuild
  version: {{ version }}

source:
  url: https://github.com/evanw/esbuild/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 481201f00848594f5850ac32ddf9d4d21047e5a4c306485fb7461dd4d14d6fa2

build:
  number: 0
  # Go-built binaries do not react well to prefix replacement. They don't need it, though.
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - make     # [unix]
    - m2-base  # [win]
    - m2-make  # [win]
    - nodejs >=14

test:
  commands:
    - esbuild --version

about:
  home: https://esbuild.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An extremely fast javascript bundler
  dev_url: https://github.com/evanw/esbuild

extra:
  recipe-maintainers:
    - msarahan
