{% set version = "0.15.3" %}

package:
  name: esbuild
  version: {{ version }}

source:
  url: https://github.com/evanw/esbuild/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7749207f015c42812cf2d1dab8b10fdeefd986142e1444cb470d9126792c4d0d

build:
  number: 0
  # Go-built binaries do not react well to prefix replacement. They don't need it, though.
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - make     # [unix]
    - m2-base  # [win]
    - m2-make  # [win]
    - nodejs

test:
  commands:
    - esbuild --version

about:
  home: https://esbuild.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An extremely fast javascript bundler
  dev_url: https://github.com/evanw/esbuild

extra:
  recipe-maintainers:
    - msarahan
