{% set version = "0.15.15" %}

package:
  name: esbuild
  version: {{ version }}

source:
  url: https://github.com/evanw/esbuild/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4143a346e4631f22cecc35094e3f1af569b5cdf87e0e0f91856d452761217c5d

build:
  number: 0
  # Go-built binaries do not react well to prefix replacement. They don't need it, though.
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - make     # [unix]
    - m2-base  # [win]
    - m2-make  # [win]
    - nodejs >=14

test:
  commands:
    - esbuild --version

about:
  home: https://esbuild.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An extremely fast javascript bundler
  dev_url: https://github.com/evanw/esbuild

extra:
  recipe-maintainers:
    - msarahan
