{% set version = "0.25.0" %}

package:
  name: esbuild
  version: {{ version }}

source:
  url: https://github.com/evanw/esbuild/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c200f558d25a36513b830af8f9a09b5b8924807536f9c3b6b6024c301fee3b2c

build:
  number: 0
  # Go-built binaries do not react well to prefix replacement. They don't need it, though.
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - make     # [unix]
    - m2-base  # [win]
    - m2-make  # [win]
    - nodejs >=14

test:
  commands:
    - esbuild --version

about:
  home: https://esbuild.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An extremely fast javascript bundler
  dev_url: https://github.com/evanw/esbuild

extra:
  recipe-maintainers:
    - xhochy
    - msarahan
