schema_version: 1

context:
  version: "0.27.0"

package:
  name: esbuild
  version: ${{ version }}

source:
  url: https://github.com/evanw/esbuild/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a4fd2af11353d41999b51bfa4276cbdd562b5f5fc19b3ca56ab69a520b176529

build:
  # Go-built binaries do not react well to prefix replacement. They don't need it, though.
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - if: unix
      then: make
    - if: win
      then:
        - m2-base
        - m2-make
    - nodejs >=14

tests:
  - script:
      - esbuild --version

about:
  license: MIT
  license_file: LICENSE.md
  summary: An extremely fast javascript bundler
  homepage: https://esbuild.github.io/
  repository: https://github.com/evanw/esbuild

extra:
  recipe-maintainers:
    - xhochy
    - msarahan
